import Head from 'next/head';
import { NavBar } from '@/components/NavBar';
import { GridCategories } from '@/components/GridCategories';
import { useEffect, useState } from 'react';
import { getItems } from '@/helpers/getItems';

export default function Home() {
  const [items, setItems] = useState([]);
  const [itemsCartMenu, setItemsCartMenu] = useState([]);
  const [viewMenu, setViewMenu] = useState(false)

  const insertItem = (product) => {
    if (!itemsCartMenu.some((item) => item.id === product.id)) {
      setItemsCartMenu([...itemsCartMenu, { ...product, quantity: 1 }])
      setViewMenu(true)
    } else {
      setItemsCartMenu(itemsCartMenu.map(item => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item))
      setViewMenu(true)
    }
  }

  const getMenu = () => {
    setViewMenu(!viewMenu)
  }

  const itemsApi = async () => {
    let response = await getItems();
    setItems(response);
  }

  useEffect(() => {
    itemsApi();
  }, [])

  console.log(itemsCartMenu);

  return (
    <>
      <Head>
        <title>Fake Store</title>
        <meta charSet='UTF-8' />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar menu={viewMenu} view={getMenu} itemMenu={itemsCartMenu} />
      <GridCategories items={items} insertItem={insertItem} />
    </>
  )
}
